export const types = {
  CHANGE_SORT_CRITERION: "CHANGE_SORT_CRITERION",
  SET_SORT_CRITERION: "SET_SORT_CRITERION",
  GET_GOOD: "GET_GOOD",
  SET_GOOD: "SET_GOOD",
  REQUEST_COMPONENTS: "REQUEST_COMPONENTS",
  SET_GOODS: "SET_GOODS",
  ERROR: "ERROR"
}