export const types = {
  CHANGE_SORT_CRITERION: "CHANGE_SORT_CRITERION",
  SORT_BY_PRICE_ASC: "SORT_BY_PRICE_ASC",
  SORT_BY_PRICE_DESC: "SORT_BY_PRICE_DESC",
  SORT_BY_NAME_ASC: "SORT_BY_NAME_ASC",
  SORT_BY_NAME_DESC: "SORT_BY_NAME_DESC",
  REQUEST_COMPONENTS: "REQUEST_COMPONENTS",
  SET_GOODS: "SET_GOODS",
  ERROR: "ERROR"
}